### ISSUE TITLE
VS 2022 addin isn't working: `System.UnauthorizedAccessException: Access to the path 'CSharpier.dll' is denied.`

### ISSUE THREAD

**Issue by viceice** [belav/csharpier#1048]
Since VS 2022 v17.8.0 charpier is no longer working and i get that logging:

```
Starting
Exception: System.UnauthorizedAccessException: Access to the path 'CSharpier.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CSharpier.VisualStudio.CustomPathInstaller.EnsureVersionInstalled(String version)
   at CSharpier.VisualStudio.CSharpierProcessProvider.SetupCSharpierProcess(String directory, String version)
   at CSharpier.VisualStudio.CSharpierProcessProvider.FindAndWarmProcess(String filePath)
   at CSharpier.VisualStudio.CSharpierPackage.<InitializeAsync>d__1.MoveNext()
```

**Comment by viceice** [comment]
OK, it seems vscode had somehow blocked it 😕
