### ISSUE TITLE
Failing in Rider

### ISSUE THREAD

**Issue by chrisdrobison** [belav/csharpier#1050]
Getting an error in Rider saying it can't setup Csharpier. Here are the Rider logs for your perusal. I did go to that AppData folder and even cleared it out. It would come back on restart, but the csharpier exe would never get put back into it.

```
2023-11-29 09:08:51,755 [  21210] SEVERE - #c.i.c.CSharpierLogger - Cannot run program "C:\Users\i52017\AppData\Local\CSharpier\0.26.3\dotnet-csharpier" (in directory "C:\Users\i52017\AppData\Local\CSharpier\0.26.3"): CreateProcess error=2, The system cannot find the file specified
java.lang.Throwable: Cannot run program "C:\Users\i52017\AppData\Local\CSharpier\0.26.3\dotnet-csharpier" (in directory "C:\Users\i52017\AppData\Local\CSharpier\0.26.3"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.csharpier.ProcessHelper.ExecuteCommand(ProcessHelper.java:53)
	at com.intellij.csharpier.CustomPathInstaller.validateInstall(CustomPathInstaller.java:54)
	at com.intellij.csharpier.CustomPathInstaller.ensureVersionInstalled(CustomPathInstaller.java:45)
	at com.intellij.csharpier.CSharpierProcessProvider.setupCSharpierProcess(CSharpierProcessProvider.java:210)
	at com.intellij.csharpier.CSharpierProcessProvider.findAndWarmProcess(CSharpierProcessProvider.java:94)
	at com.intellij.csharpier.CSharpierProcessProvider.<init>(CSharpierProcessProvider.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:95)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.intellij.csharpier.CSharpierProcessProvider.getInstance(CSharpierProcessProvider.java:56)
	at com.intellij.csharpier.CSharpierStartup.runActivity(CSharpierStartup.java:12)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:327)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:264)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:263)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:263)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-11-29 09:08:51,757 [  21212] SEVERE - #c.i.c.CSharpierLogger - JetBrains Rider 2023.2.3  Build #RD-232.10203.29
2023-11-29 09:08:51,757 [  21212] SEVERE - #c.i.c.CSharpierLogger - JDK: 17.0.8.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-11-29 09:08:51,757 [  21212] SEVERE - #c.i.c.CSharpierLogger - OS: Windows 11
2023-11-29 09:08:51,757 [  21212] SEVERE - #c.i.c.CSharpierLogger - Plugin to blame: CSharpier version: 1.5.0
2023-11-29 09:08:51,760 [  21215]   INFO - STDERR - java.io.IOException: Cannot run program "C:\Users\i52017\AppData\Local\CSharpier\0.26.3\dotnet-csharpier" (in directory "C:\Users\i52017\AppData\Local\CSharpier\0.26.3"): CreateProcess error=2, The system cannot find the file specified
2023-11-29 09:08:51,760 [  21215]   INFO - STDERR - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
2023-11-29 09:08:51,760 [  21215]   INFO - STDERR - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at com.intellij.csharpier.ProcessHelper.ExecuteCommand(ProcessHelper.java:32)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at com.intellij.csharpier.CustomPathInstaller.validateInstall(CustomPathInstaller.java:54)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at com.intellij.csharpier.CustomPathInstaller.ensureVersionInstalled(CustomPathInstaller.java:45)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at com.intellij.csharpier.CSharpierProcessProvider.setupCSharpierProcess(CSharpierProcessProvider.java:210)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at com.intellij.csharpier.CSharpierProcessProvider.findAndWarmProcess(CSharpierProcessProvider.java:94)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at com.intellij.csharpier.CSharpierProcessProvider.<init>(CSharpierProcessProvider.java:47)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2023-11-29 09:08:51,761 [  21216]   INFO - STDERR - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:95)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.csharpier.CSharpierProcessProvider.getInstance(CSharpierProcessProvider.java:56)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.csharpier.CSharpierStartup.runActivity(CSharpierStartup.java:12)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:327)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:72)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:264)
2023-11-29 09:08:51,762 [  21217]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:263)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:263)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:72)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:181)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at java.base/java.lang.ProcessImpl.create(Native Method)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
2023-11-29 09:08:51,763 [  21218]   INFO - STDERR - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
2023-11-29 09:08:51,764 [  21219]   INFO - STDERR - 	... 38 more
2023-11-29 09:08:51,764 [  21219]   WARN - #c.i.c.CSharpierLogger - Exception while running 'dotnet csharpier --version' in C:\Users\i52017\AppData\Local\CSharpier\0.26.3
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "com.intellij.csharpier.ProcessHelper.ExecuteCommand(String[], java.util.Map, java.io.File)" is null
	at com.intellij.csharpier.CustomPathInstaller.validateInstall(CustomPathInstaller.java:54)
	at com.intellij.csharpier.CustomPathInstaller.ensureVersionInstalled(CustomPathInstaller.java:45)
	at com.intellij.csharpier.CSharpierProcessProvider.setupCSharpierProcess(CSharpierProcessProvider.java:210)
	at com.intellij.csharpier.CSharpierProcessProvider.findAndWarmProcess(CSharpierProcessProvider.java:94)
	at com.intellij.csharpier.CSharpierProcessProvider.<init>(CSharpierProcessProvider.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:95)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.intellij.csharpier.CSharpierProcessProvider.getInstance(CSharpierProcessProvider.java:56)
	at com.intellij.csharpier.CSharpierStartup.runActivity(CSharpierStartup.java:12)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:327)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:264)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:263)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:263)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by belav** [comment]
If there is never an exe in that directory, that seems to indicate that the extension is failing to install it to that location. The steps [here](https://csharpier.com/docs/EditorsTroubleshooting) show how to install dotnet to the location and then check the install. Perhaps the install is failing.

Also I just noticed that page's formatted is a little off. It should be fixed shortly.

**Comment by jussibility** [comment]
I'm seeing the same error. I tried following the steps but  it did not help.
