### ISSUE TITLE
Latest CSharpier extension fails to load in Visual Studio 2022

### ISSUE THREAD

**Issue by polewskm** [belav/csharpier#1407]
**Environments**
- IDE Version: Visual Studio Professional 2022 v17.12.3
- Extension Version: 1.9.0
- CSharpier Version:  0.30.3
- Operating System: 22H2 (OS Build 19045.5247)
- .csharpierrc Settings: None
- .editorconfig Settings: None

**Log Output**
- Log file: `C:/Users/marcinp/AppData/Roaming/Microsoft/VisualStudio/17.0_85c1477a/ActivityLog.xml`
- Contents:
```
SetSite failed for package [CSharpierPackage]Source: 'System' Description: Value cannot be null.
Parameter name: path
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at CSharpier.VisualStudio.CSharpierOptions.<InitializeHotReloadWatcherAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpier.VisualStudio.CSharpierOptions.<CreateAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass20_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at CSharpier.VisualStudio.CSharpierOptions.get_Instance()
   at CSharpier.VisualStudio.CustomPathInstaller..ctor(CSharpierPackage package)
   at CSharpier.VisualStudio.CustomPathInstaller.GetInstance(CSharpierPackage package)
   at CSharpier.VisualStudio.CSharpierProcessProvider..ctor(CSharpierPackage package)
   at CSharpier.VisualStudio.CSharpierProcessProvider.GetInstance(CSharpierPackage package)
   at CSharpier.VisualStudio.CSharpierPackage.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.Close()
```

**Steps to reproduce**
1. Install Visual Studio 2022 Professional
1. Install CSharpier extension
1. Start Visual Studio without opening a solution/project
1. Goto `Tools | Options | CSharpier`

**Expected behavior**
No error popup.

**Actual behavior**
![image](https://github.com/user-attachments/assets/1d4e5d0a-0831-4cb9-97c3-fd3e513ac083)

**Comment by belav** [comment]
I pushed out a fix for this in version 1.9.1 of the extension, thanks for the bug report!
