### ISSUE TITLE
VS Extension v1.9.3 fails to load

### ISSUE THREAD

**Issue by Kurren123** [belav/csharpier#1414]
**Environments**
- IDE Version: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current, Version 17.10.3
- Extension Version: 1.9.3
- CSharpier Version:   0.30.3
- Operating System: Windows 11, Version 10.0.22631 Build 22631
- .csharpierrc Settings: None
- .editorconfig Settings: None

**Screenshot**
![image](https://github.com/user-attachments/assets/18e7a2b9-4695-4699-a77e-b3f1dc9b4cbc)

**Log Output**
```
SetSite failed for package [CSharpierPackage]Source: 'CSharpier.VisualStudio' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.12.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.12.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Threading, Version=17.12.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at CSharpier.VisualStudio.CSharpierPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Steps to reproduce**
Install the extension, open Visual Studio 2022

**Comment by belav** [comment]
Sorry about that - it appears that updating the `Microsoft.VisualStudio.SDK` package reference makes the extension depend on that newer version of VisualStudio. I reverted those updates and I believe things will work properly in older versions now. I was on the latest so couldn't reproduce it.

**Comment by Kurren123** [comment]
No worries, thanks for your help!
