### ISSUE TITLE
Rider does not detect csharpier

### ISSUE THREAD

**Issue by gschuager** [belav/csharpier#571]
I'm trying to use the Rider plugin.
I installed csharpier globally with `dotnet install -g csharpier` but Rider doesn't seem to detect it.

![image](https://user-images.githubusercontent.com/139658/150886781-df47afe1-a3f5-4f13-ac5c-1f51234c104a.png)

Do you have any suggestion about what can I look to troubleshoot this?

**Comment by belav** [comment]
If you installed csharpier while Rider was open, the plugin isn't smart enough to detect that yet. Restarting Rider would resolve that.
You can also try the 1.2.0 beta version which will work with a local tool or global tool. https://github.com/belav/csharpier/releases/tag/rider-1.2.0-beta1
Otherwise there may be more information in the idea.log file - https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by belav** [comment]
Another thought.
Try running the following in the same folder where your project is
```
dotnet csharpier --version
```
That should just be outputting a version number

**Comment by gschuager** [comment]
Thank you, version 1.2.0 beta1 seems to work ok.

FYI, I was getting the following error in the logs:

```
2022-01-25 08:54:39,712 | INFO  | ReformatWithCSharpierAction    | Using command dotnet csharpier
2022-01-25 08:54:39,721 | INFO  | RiderApplicationLoadListener   | [STDOUT] 00:16 ERROR: Cannot run program "dotnet": error=2, No such file or directory
2022-01-25 08:54:39,721 | WARN  | RiderApplicationLoadListener   | [STDERR] java.io.IOException: Cannot run program "dotnet": error=2, No such file or directory
2022-01-25 08:54:39,721 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
2022-01-25 08:54:39,721 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.Runtime.exec(Runtime.java:592)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.Runtime.exec(Runtime.java:416)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.Runtime.exec(Runtime.java:313)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.csharpier.CSharpierService.execCmd(CSharpierService.java:47)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.csharpier.CSharpierService.setupCSharpierProcess(CSharpierService.java:60)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.csharpier.CSharpierService.<init>(CSharpierService.java:29)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
2022-01-25 08:54:39,722 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:41)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:40)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
2022-01-25 08:54:39,723 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.csharpier.CSharpierService.getInstance(CSharpierService.java:42)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.csharpier.CSharpierStartup.runActivity(CSharpierStartup.java:11)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:312)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:293)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:288)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:245)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:645)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:244)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:62)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:144)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:239)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:62)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3$1.run(StartupManagerImpl.kt:189)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
2022-01-25 08:54:39,724 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:277)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:255)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3.run(StartupManagerImpl.kt:189)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] Caused by: java.io.IOException: error=2, No such file or directory
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
2022-01-25 08:54:39,725 | WARN  | RiderApplicationLoadListener   | [STDERR] 	... 57 more
2022-01-25 08:54:39,726 | INFO  | ReformatWithCSharpierAction    | CSharpier version: null
```
