### ISSUE TITLE
Support scoped variables

### ISSUE THREAD

**Issue by Dragemil** [belav/csharpier#839]
https://github.com/dotnet/csharplang/blob/d45a4817470319e08707d2426b9ad4edebe99676/proposals/low-level-struct-improvements.md#examples-scoped-locals

Currently csharpier throws when it is encountered.
```
Can't handle ScopedTypeSyntax
     at CSharpier.SyntaxNodeComparer.Compare(ValueTuple`2 original, ValueTuple`2 formatted) in /home/runner/work/csharpier/csharpier/Src/CSharpier/SyntaxNodeComparer.generated.cs:line 516
     at CSharpier.SyntaxNodeComparer.AreEqualIgnoringWhitespace(SyntaxNode originalStart, SyntaxNode formattedStart) in /home/runner/work/csharpier/csharpier/Src/CSharpier/SyntaxNodeComparer.cs:line 114
     at CSharpier.SyntaxNodeComparer.CompareSourceAsync(CancellationToken cancellationToken) in /home/runner/work/csharpier/csharpier/Src/CSharpier/SyntaxNodeComparer.cs:line 43
     at CSharpier.Cli.CommandLineFormatter.PerformFormattingSteps(FileToFormatInfo fileToFormatInfo, IFormattedFileWriter formattedFileWriter, CommandLineFormatterResult commandLineFormatterResult, FileIssueLogger fileIssueLogger, PrinterOptions printerOptions, CommandLineOptions commandLineOptions, IFormattingCache formattingCache, CancellationToken cancellationToken) in /home/runner/work/csharpier/csharpier/Src/CSharpier.Cli/CommandLineFormatter.cs:line 398
```

**Comment by belav** [comment]
I thought I had CSharpier handling syntax nodes that it wasn't familiar with correctly but I missed the code in `SyntaxNodeComparer`.

If you want a workaround `dotnet csharpier . --fast` bypasses the `SyntaxNodeComparer` code or `// csharpier-ignore` is always an option.

**Comment by Dragemil** [comment]
Thanks!

Didn't try `dotnet csharpier . --fast` back then, but having `// csharpier-ignore` on the variable or even whole method still had csharpier throwing. Same for the scoped ignores.
