### ISSUE TITLE
Chsarpier freezes Rider

### ISSUE THREAD

**Issue by ChristianSauer** [belav/csharpier#926]
When I refactor Code, Csharpier freezes the UI sometimes.
Unfortunately it's impossible to reproduce reliably.
It mostly happens when I reformat code and the code is broken for a moment.

Can I find logs somewhere?

Usually killing the Csharpier Task via Taskmanager and then reenabling the Plugin unfreezes the Ui.

**Comment by belav** [comment]
I believe I ran into issues like this early on but I thought they were fixed. Hopefully the logs will give some more information.
Instructions for getting to them are https://github.com/belav/csharpier/tree/main/Src/CSharpier.Rider#troubleshooting
You'll want to enable debug logging first, and restart rider.

**Comment by nzjoel1234** [comment]
I have seen this issue. I think it happens more when I am working on code containing `Expression<Func<...>` this may not be accurate but it seems like it to me.

**Comment by ShawnTheBeachy** [comment]
I've hit this issue 3 times in 3 hours so far this morning. I'm not sure if it's related, but it looks like a few minutes after I start Rider, a second `dotnet-csharpier` process is spawned. Perhaps the two processes are hanging each other up? Or maybe this is expected behavior 🤷 

<img width="487" alt="image" src="https://github.com/belav/csharpier/assets/9746255/0e8d09ed-309a-455a-80e6-2e76500340f9">

**Comment by belav** [comment]
So I realized tonight that the VS plugin has a similar issue, where it csharpier would freeze if another plugin happened to run at the same time. I implemented basically the same code from https://github.com/belav/csharpier/pull/890 into the rider plugin, and did some testing where I forced csharpier to freeze and ensured it restarts successfully. 

So even not being able to reproduce the problem I believe that 1.3.9 will prevent the freezes (or at least keep them to just 3 seconds). Jetbrains does have to approve plugins, which may take a day or two before it is available.

**Comment by belav** [comment]
> Looks like it's working! Updated the plugin and just got a freeze, but it unfroze again within a few seconds.
> 
> EDIT: While working in some problem files, I've gotten roughly 10 freezes so far today. Each time it unfroze again without issue.

Is it possible to share one of those files? It would seem odd that specific files would cause the problem if they promptly start working later. Ideally I'd like to figure out the cause, because if it is happening 10 times a day that can still be annoying.

Another option would be for you to try running the plugin locally in debug via intellij. If you can debug the code when it occurs maybe it is possible to understand why it occurs.

**Comment by ShawnTheBeachy** [comment]
Unfortunately those files are no longer in the state they were in that caused the hangs. If I get another file that does it, I'll send you a copy.

**Comment by belav** [comment]
If it seems to be the same files, it could be that there is a certain sequence of characters that is causing the issue. The plugin streams the file contents to the actual csharpier process, which then writes it back out formatted on std out. With some special characters as delimiters. It is on the list to redo this using something like protobuf + named pipes, but it was good enough for a first pass. I was also hoping that native AOT would become viable. The csharpier process stays running because starting it up is slow compared to the actual formatting of code. I tested out an AOT version of csharpier, and it formatted fast enough to not require leaving it running. As far as I know it isn't possible yet to distribute a dotnet tool.

**Comment by ShawnTheBeachy** [comment]
@belav I have a file which I'm in the middle of refactoring and is freezing up on me frequently. There's no way I've found to reliably make it freeze, but it's happening pretty often. How shall I send you the file?

**Comment by belav** [comment]
@ShawnTheBeachy I don't suppose it is in a public repo? You can also just attach it to a comment, may have to zip it first.

**Comment by ShawnTheBeachy** [comment]
It's not public, no. I've uploaded a copy with the only change being to substitute "CorpName" for the company name in the file.
The way I was able to reproduce it reliably was to use Rider's "Convert to '?:' operator" context action on line 70, then position my cursor on line 69 (blank) and hit save. If I hit save without moving my cursor from line 70, it did not freeze. I'm not sure if line 69 was crucial to the freeze, or if just putting my cursor on any line other than 70 would have done it.

[ProblemFile.zip](https://github.com/belav/csharpier/files/12542140/ProblemFile.zip)

**Comment by belav** [comment]
@ShawnTheBeachy I was able to recreate this just by changing some text on line 71, I was worried I would have to go down the route of getting the file compile-able to use the "Convert to '?:' operator". I can produce it reliably so I'm hoping I can track down a proper fix. Thanks for sharing it!

**Comment by belav** [comment]
The problem ended up being that the csharpier process was writing compilation errors to stderror. Nothing in the rider plugin was reading the error stream, so eventually it would hang. I was able to reproduce it with that file because without having the rest of the classes in the using statements, there were 26 compilations errors. Every other time I formatted it the error stream filled up and hung. The seemingly randomness of seeing it makes a lot more sense now.

I uploaded version 1.3.10 of the plugin, which will be available in a couple of days.

**Comment by leonkuchinka** [comment]
I am using 1.3.10 of the plugin on MacOS 13.4 and Rider 2023.2. I am still running into the problem, where CSharpier causes Rider to freeze. Furthermore, when I try to format a file it fails and Rider provides me with the following stacktrace in the IDE internal errors window:
```
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:320)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
	at com.intellij.csharpier.CSharpierProcessPipeMultipleFiles.lambda$formatFile$0(CSharpierProcessPipeMultipleFiles.java:60)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by belav** [comment]
@lemaku I ended up trying to code a fix before getting more info and probably should have started with getting more info, but either way I have some auto retry logic built in https://github.com/belav/csharpier/releases/tag/rider-1.3.11-beta1, which may help.

Some questions

- Is this happening for every file? If so I don't know it my retry logic would help.
- Has this ever worked for you?
- Is there anything in the logs before that error occurs that may help narrow down the problem? Rider logs are kinda hidden compared to the other IDEs - https://github.com/belav/csharpier/tree/main/Src/CSharpier.Rider#troubleshooting

**Comment by lemaku** [comment]
@belav Sorry for the late response. I ended up sticking to a different tool, but wanted to follow up on your questions:

- Yes, it was happening for every file
- No, it has not worked for me - although I can only talk about the specific version I mentioned earlier
- I looked into the logs, but couldn't find anything that is useful in any way - sorry

**Comment by viniciuschiele** [comment]
@belav I've just upgraded `csharpier` from v0.25.0 to v0.26.0 and Rider is frozen every time I save a file, rolling it back to v0.25.0 works just fine.

I also noticed that after installing the new version, Rider requested access to a Network volume on my Mac (I don't recall exactly what was the message)

I'm using `dotnet tool restore` and `dotnet-tools.json` to install `csharpier`.

Mac: 14.0
Plugin: 1.3.10
Rider: 2023.2.3

Rider logs:

```
2023-11-07 10:01:53,453 [    911]   INFO - #c.i.d.DebugLogManager - Set DEBUG for the following categories: #com.intellij.csharpier.CSharpierLogger, com.intellij.csharpier.CSharpierLogger
2023-11-07 10:02:01,643 [   9101]   FINE - #c.i.c.CSharpierLogger - Ensure there is a csharpier process for /xxxxxxx/MyProject/src/Application/Wizards/Requests
2023-11-07 10:02:01,644 [   9102]   FINE - #c.i.c.CSharpierLogger - Looking for /xxxxxxx/MyProject/src/Application/Wizards/Requests/.config/dotnet-tools.json
2023-11-07 10:02:01,644 [   9102]   FINE - #c.i.c.CSharpierLogger - Looking for /xxxxxxx/MyProject/src/Application/Wizards/.config/dotnet-tools.json
2023-11-07 10:02:01,689 [   9147]   FINE - #c.i.c.CSharpierLogger - Looking for /xxxxxxx/MyProject/src/Application/.config/dotnet-tools.json
2023-11-07 10:02:01,689 [   9147]   FINE - #c.i.c.CSharpierLogger - Looking for /xxxxxxx/MyProject/src/.config/dotnet-tools.json
2023-11-07 10:02:01,689 [   9147]   FINE - #c.i.c.CSharpierLogger - Looking for /xxxxxxx/MyProject/.config/dotnet-tools.json
2023-11-07 10:02:01,691 [   9149]   FINE - #c.i.c.CSharpierLogger - Found version 0.26.0 in /xxxxxxx/MyProject/.config/dotnet-tools.json
2023-11-07 10:02:01,698 [   9156]   FINE - #c.i.c.CSharpierLogger - Running /xxxxxxx/.cache/csharpier/0.26.0/dotnet-csharpier --version in /xxxxxxx/.cache/csharpier/0.26.0
2023-11-07 10:02:02,057 [   9515]   FINE - #c.i.c.CSharpierLogger - dotnet csharpier --version output: 0.26.0+70db9c7bf96bf143942bfa4c75efbf54aa3a0484
2023-11-07 10:02:02,147 [   9605]   FINE - #c.i.c.CSharpierLogger - Running dotnet tool install csharpier --version 0.26.0 --tool-path /xxxxxxx/.cache/csharpier/0.26.0
2023-11-07 10:02:08,675 [  16133]   FINE - #c.i.c.CSharpierLogger - Adding new version 0.26.0 process for /xxxxxxx/MyProject/src/Application/Wizards/Requests
2023-11-07 10:02:08,685 [  16143]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:11,687 [  19145]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:11,700 [  19158]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:14,700 [  22158]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:14,708 [  22166]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:17,713 [  25171]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:17,717 [  25175]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:20,723 [  28181]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:20,731 [  28189]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:23,733 [  31191]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:23,738 [  31196]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:24,758 [  32216]   FINE - #c.i.c.CSharpierLogger - SaveDocumentAction for DocumentImpl[file:///xxxxxxx/MyProject/src/Application/Wizards/Requests/GetWizardHandler.cs]
2023-11-07 10:02:26,740 [  34198]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:26,744 [  34202]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:29,748 [  37206]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:29,753 [  37211]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:32,758 [  40216]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:32,762 [  40220]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:35,767 [  43225]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:35,772 [  43230]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:38,777 [  46235]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:38,782 [  46240]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:41,785 [  49243]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:41,790 [  49248]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:44,795 [  52253]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:44,799 [  52257]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:47,804 [  55262]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:47,810 [  55268]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:50,814 [  58272]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:50,820 [  58278]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:53,824 [  61282]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:53,829 [  61287]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:56,831 [  64289]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:56,836 [  64294]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:02:59,846 [  67304]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:02:59,851 [  67309]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format
2023-11-07 10:03:03,546 [  71004]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-07 10:03:03,552 [  71010]   FINE - #c.i.c.CSharpierLogger - Warm CSharpier with initial format```

Thanks

**Comment by belav** [comment]
@viniciuschiele I didn't recreate this exactly, but that could be because I am running on windows. With windows it is not reformatting files, and the dotnet-csharpier process appears to be failing to start with the following. I found this in the event viewer in windows, not sure what the mac equivalent would be.

```
Path: C:\Users\bela\AppData\Local\CSharpier\0.26.0\dotnet-csharpier.exe
Message: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Users\bela\AppData\Local\CSharpier\0.26.0\.store\csharpier\0.26.0\csharpier\0.26.0\tools\net8.0\any\dotnet-csharpier.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Users\bela\AppData\Local\CSharpier\0.26.0\.store\csharpier\0.26.0\csharpier\0.26.0\tools\net8.0\any\dotnet-csharpier.runtimeconfig.json' file and specify the appropriate framework.
```

**Comment by belav** [comment]
actually, that appeared to be a failed install of the 0.26.0 version. wiping out my `C:\Users\bela\AppData\Local\CSharpier\0.26.0\` folder after closing rider, and restarting fixed that problem for me.

You can see if doing the same for `/xxxxxxx/.cache/csharpier/0.26.0` works.

Otherwise I was thinking the problem could be related to the new editorconfig support. Do you have any editorconfig files in your solution? What about any .csharpierrc files?

**Comment by riandrake** [comment]
Hi, I'm experiencing the issue exactly as @viniciuschiele describes - also Mac, also the Network volume prompt.

I can confirm that deleting my local .editorconfig stopped Rider from freezing.

This is my first attempt at getting CSharpier working in our project, so I can't say anything about previous versions. But it froze 100% of the time I saved a file in Rider until I deleted the editor config.

**Comment by belav** [comment]
@riandrake if your editorconfig had duplicated sections, then I do have a fix coming out shortly. See https://github.com/belav/csharpier/issues/989#issuecomment-1802542171

**Comment by viniciuschiele** [comment]
I'm not using `.editorconfig`, I only have `.csharpierrc.yaml`

**Comment by belav** [comment]
@viniciuschiele if you try a new project with the same .csharpierrc.yaml do you get the same issue?
Do you know if the csharpier process is crashing when this happens? Right now rider assumes it is hung after waiting a few seconds for a response, but if it is crashing immediately then it must be throwing some kind of an exception. 

The reason it freezes on typing is because behind the scenes the plugin tries to ensure csharpier is ready to format a file when you do hit save. When I added the logic to detect a hung csharpier I neglected to add a bail condition, so it gets stuck in a loop right now.

I created #995 yesterday to try to improve the situation when the csharpier process is crashing. And I have a few other issues on the 0.26.0 milestone around improvements to the extensions that I'm hoping to get to next. I'll be out of town for a long weekend starting tonight so you may be stuck on 0.25.0 for a bit.

**Comment by viniciuschiele** [comment]
@belav I tried a new project with/without `.csharpierrc.yaml`, same issue.

The process `dotnet-csharpier` keeps crashing every few seconds.

**Comment by jstaro** [comment]
FWIW, people using macOS on our team encountered this same issue on v0.26.1, using `.editorconfig`. It works fine on Windows 11, though.

**Comment by MonstraG** [comment]
Just updated from 0.25.0 to 0.26.2, my logs are full of
```
2023-11-16 09:49:55,079 [  88663]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-16 09:49:58,082 [  91666]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-16 09:50:01,085 [  94669]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-16 09:50:04,087 [  97671]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-16 09:50:07,090 [ 100674]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
2023-11-16 09:50:10,093 [ 103677]   WARN - #c.i.c.CSharpierLogger - CSharpier process appears to be hung, restarting it.
```

**Comment by belav** [comment]
I believe there are two possible causes for the issues with freezing, both of which appeared on an older install of windows I switched to because I was having trouble compiling the rider extension on my fresh install. 

1. When the plugin installs csharpier to the custom location, sometimes that install doesn't complete correctly. I have some code that tries to detect this and reinstall it, but I ran into a different type of install failure
2. If someone has an older preview version of net8 installed, but not at least the version of net8 used to build csharpier, then csharpier will fail to run. It appears that from a custom location it always tries to use the latest dotnet sdk, and I'm not sure if there is a good way to get it to respect a global.json if there is one in the project.

As a resolution

1. Close IDEs
2. Try running `C:\Users\[UserName]\AppData\Local\CSharpier\[CSharpierVersion]\dotnet-csharpier --version` or `$Home/.cache/csharpier/[CSharpierVersion] --version`. CSharpierVersion may contain a git hash.
3. If that fails because of a missing net8 sdk install that
4. If that fails in another way wipe out the folder
5. Run `dotnet tool install csharpier --version [CSharpierVersion] --tool-path [PathFromAbove]` - where `[PathFromAbove]` does not include `dotnet-csharpier`
6. Check step 1 again

I'm modifiying all of the extensions to detect these conditions and supply an error message that will allow users to resolve the problem.

**Comment by MonstraG** [comment]
If I don't forget, I'll try that, but for additional info: I'm on linux and I did not update to .Net 8 yet, still on .net 7

**Comment by belav** [comment]
I didn't have time to fully test this but the new [1.5.0-beta2](https://github.com/belav/csharpier/releases/tag/rider-1.5.0-beta2) version will do a better job of logging and reporting failures starting CSharpier. Also if you do get the popup with a read more link, I didn't get a chance to finish up that troubleshooting page.

@viniciuschiele I'm curious if this will show the reason why the plugin is unable to run CSharpier for you.

**Comment by viniciuschiele** [comment]
@belav I wasn't aware of the plugin beta versions.

I tried `1.5.0-beta2` and `1.3.11-beta1`, both versions fix the issue, Rider no longer freezes.

I rolled back to version `1.3.10` just to be sure and the issue came back.

**Comment by belav** [comment]
I released `1.5.0` last week which I believe has resoled this issue.

**Comment by viniciuschiele** [comment]
Yes, it is working now. Thanks
